AllCops:
  TargetRubyVersion: 2.4
  DefaultFormatter: fuubar
  DisplayStyleGuide: true
  DisplayCopNames: false
#require: rubocop-rspec
Style/AsciiComments:
  Enabled: false # we use german comments to document relevant methods for the pupils
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context'] # RSpec uses a DSL where large blocks are okay, see https://stackoverflow.com/questions/40934345/rubocop-25-line-block-size-and-rspec-tests
